### ISSUE TITLE
Flathub version not working

### ISSUE THREAD

**Issue by vidje** [flathub/org.unknown_horizons.UnknownHorizons#2]
Hi, I'm on F33, proprietary nvidia drivers (460.39) and the game won't start due to:
```X Error of failed request:  GLXBadDrawable
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  315
  Current serial number in output stream:  315```

**Comment by tintou** [comment]
Unfortunately this is not linked to the Flatpak package but an issue with either the FIFE engine or the nVidia drivers.
See a related bug report for last year: https://github.com/unknown-horizons/unknown-horizons/issues/2936

I'm also able to reproduce the crash here with a nvidia driver and a native Ubuntu package.

**Comment by LinuxDonald** [comment]
@tintou could you rebuild the package with lastest git changes?
